# Generated by Django 2.2 on 2021-02-13 20:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('likes', models.IntegerField(default=0)),
                ('img', models.ImageField(default='none.png', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept_text', models.CharField(default='', max_length=200)),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gluten.Recept')),
            ],
        ),
    ]
