# Generated by Django 2.2 on 2021-02-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gluten', '0002_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
