# Generated by Django 2.2 on 2021-02-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gluten', '0004_categor'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='types',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gluten.Categor'),
        ),
    ]
