# Generated by Django 2.2 on 2021-02-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluten', '0005_recept_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='img',
            field=models.ImageField(default='none.png', upload_to='uploads/Recepts/'),
        ),
    ]
