# Generated by Django 2.2 on 2021-02-21 12:57

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gluten', '0006_text_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='comp',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='text',
            name='img',
            field=models.ImageField(blank=True, upload_to='uploads/Recepts/'),
        ),
    ]
