# Generated by Django 2.2 on 2021-02-21 12:59

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gluten', '0007_auto_20210221_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recept',
            name='comp',
            field=jsonfield.fields.JSONField(default=''),
        ),
    ]
