# Generated by Django 2.2 on 2021-02-23 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gluten', '0008_auto_20210221_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(default='', max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='uploads/Comments/')),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gluten.Recept')),
            ],
        ),
    ]
