# Generated by Django 2.2 on 2021-02-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluten', '0010_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(default='Default', max_length=200),
        ),
    ]
